stages:
  - install
  - test

# Cache Python packages to speed up the pipeline
cache:
  paths:
    - .venv/
    - venv/
    - pip-cache/

# Step 1: Install dependencies
install_dependencies:
  stage: install
  image: python:3.11  # Python Docker image
  script:
    - python -m venv venv  # Create virtual environment
    - source venv/bin/activate  # Activate virtual environment
    - pip install -r requirements.txt  # Install dependencies

# Step 2: Run tests
run_tests:
  stage: test
  image: python:3.11
  script:
    - source venv/bin/activate  # Activate virtual environment
    - pytest  # Run tests using pytest
